### ISSUE TITLE
Roadmap for specification (Pre-Proposal Phase)

### ISSUE THREAD

**Issue by asraa** [wasm-signatures/design#1]
According to the thread on https://github.com/WebAssembly/WASI/issues/425, we need to follow WASI's [Process](https://github.com/WebAssembly/meetings/blob/master/process/phases.md) document:

- [x] An issue is filed on the design repository to present the idea.
- [x] Discussion on the feature occurs on the issue.
- [x] A champion or champions emerge. They may add the proposal to the proposal list at phase 0.
- [x] The champion(s) put together a somewhat-formal description of the feature in their own GitHub repository or on the issue.
- [ ] An item is added to the bi-weekly Community Group video calls's agenda through a pull request.

So we need to:
* Move the WASI issue https://github.com/WebAssembly/WASI/issues/425 to https://github.com/WebAssembly/design/issues with as much information as possible
* Discuss the feature there and link this spec repository 
* Markdown-ify and move the google doc here and make it a " somewhat-formal description "
* Add it to the agenda on a CG meeting

**Comment by jedisct1** [comment]
Thanks a lot for the recap!

The Google Doc has been markdownified. 

It certainly doesn't look like formal description, but it gives more public exposure, and we can easily track and discuss changes via pull requests.

The next CG meeting is on May 11, which gives us some time to prepare.

**Comment by asraa** [comment]
Awesome, I'll move over the WASI issue to the design repo. 

Hopefully we can also get everyone at the Friday meeting commenting and showing support.
